### ISSUE TITLE
FAQ Categories meta box missing in editor (WP 5.0)

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-simple-faq#51]
The Categories meta box is missing in the editor under WP 5.0, as reported [here](https://wordpress.org/support/topic/loss-of-faq-categories-in-the-faq-post-edit-area/).

The taxonomy needs to be registered with `'show_in_rest' => true,` for Gutenberg to display the meta box: https://github.com/studiopress/genesis-simple-faq/pull/48

**Comment by nathanrice** [comment]
Fixed in 796876b
